namespace C2Practice
{
    /// <summary>
    /// Program count of all words with no two consecutive equal characters that can be generated by
    /// reordering the given letters.
    /// </summary>
    using System;

    public class TheyAreGreen
    {
        public static void Main()
        {
            //input
            var lines = int.Parse(Console.ReadLine());
            var letters = new int[lines];
            var used = new bool[lines];
            for (int i = 0; i < lines; i++)
            {
                letters[i] = (int)char.Parse(Console.ReadLine());
            }
            uint count = 0;
            Array.Sort(letters);
            if (isValid(letters))
            {
                count++;
            }
            while (NextPermutation(letters))
            {
                if (isValid(letters))
                {
                    count++;
                }
            }
            Console.WriteLine(count);
        }

        private static bool isValid(int[] letters)
        {
            int last = letters[0];
            for (int i = 1; i < letters.Length; i++)
            {
                if (letters[i] == last)
                {
                    return false;
                }
                last = letters[i];
            }

            return true;
        }

        private static bool NextPermutation(int[] numList)
        {
            /*
             Knuths
             1. Find the largest index j such that a[j] < a[j + 1]. If no such index exists, the permutation is the last permutation.
             2. Find the largest index l such that a[j] < a[l]. Since j + 1 is such an index, l is well defined and satisfies j < l.
             3. Swap a[j] with a[l].
             4. Reverse the sequence from a[j + 1] up to and including the final element a[n].

             */
            var largestIndex = -1;
            for (var i = numList.Length - 2; i >= 0; i--)
            {
                if (numList[i] < numList[i + 1])
                {
                    largestIndex = i;
                    break;
                }
            }

            if (largestIndex < 0) return false;

            var largestIndex2 = -1;
            for (var i = numList.Length - 1; i >= 0; i--)
            {
                if (numList[largestIndex] < numList[i])
                {
                    largestIndex2 = i;
                    break;
                }
            }

            var tmp = numList[largestIndex];
            numList[largestIndex] = numList[largestIndex2];
            numList[largestIndex2] = tmp;

            for (int i = largestIndex + 1, j = numList.Length - 1; i < j; i++, j--)
            {
                tmp = numList[i];
                numList[i] = numList[j];
                numList[j] = tmp;
            }

            return true;
        }
    }
}